### ISSUE TITLE
Todo for 1.0.0

### ISSUE THREAD

**Issue by zhammer** [zhammer/faaspact-mocker#2]
- [ ] use `given` as the field holding provider states
- [ ] use `upon_receiving` as the field holding the description (maybe)
- [ ] write multiple pacts to the same file in separate sessions
- [ ] only write out pacts if pact dir argument is provided? maybe an environment variable?
- [ ] external classes should be `Request` and `Response` not `..WithMatchers`
